### ISSUE TITLE
not add to cart

### ISSUE THREAD

**Issue by lifeblood** [alexschimpf/Snkrs-Bot#2]
Traceback (most recent call last):
  File "main.py", line 78, in run
    click_buy_button(driver=driver)
  File "main.py", line 169, in click_buy_button
    wait_until_clickable(driver, xpath=xpath, duration=10)
  File "main.py", line 207, in wait_until_clickable
    WebDriverWait(driver, duration, frequency).until(EC.element_to_be_clickable((By.XPATH, xpath)))
  File "/Users/shaodong/www/Snkrs-Bot/venv/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message:

**Comment by alexschimpf** [comment]
Need more information. Also, I would recommend python 3.7.
