### ISSUE TITLE
URL issue

### ISSUE THREAD

**Issue by onetrickollie** [alexschimpf/Snkrs-Bot#26]
<img width="1140" alt="Screen Shot 2020-11-09 at 2 47 30 AM" src="https://user-images.githubusercontent.com/74182067/98534409-4a4d6b00-2239-11eb-9894-7077897884b5.png">
python3 main.py --username ******** --password ******* --url “https://www.nike.com/launch/t/space-hippie-04-this-is-trash-volt-black” --shoe-size 9.5 --driver-type chrome --shoe-type M --num-retries 4
Traceback (most recent call last):
  File "/Users/lucasliu/Documents/GitHub/Snkrs-Bot/main.py", line 290, in <module>
    run(driver=driver, shoe_type=shoe_type, username=args.username, password=args.password, url=args.url, shoe_size=args.shoe_size,
  File "/Users/lucasliu/Documents/GitHub/Snkrs-Bot/main.py", line 46, in run
    driver.maximize_window()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 736, in maximize_window
    self.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to change window state to maximized, current state is normal
  (Session info: chrome=86.0.4240.183)
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.14.6 x86_64)

Nothing really shows up on chrome after the bot ran. What should i do?
This is a newbie question but thanks to everyone who worked on this.

**Comment by leoniewgnr** [comment]
What was your solution?
