### ISSUE TITLE
datetime format explanation?

### ISSUE THREAD

**Issue by TheBoss572** [alexschimpf/Snkrs-Bot#28]
I don't understand what the datetime format actually is? For me it always outputs a ValueError: Day is out of range for month when I put for example 2020,11,12,5,20,30 and i've tried many many different formats and i'm still unable to get it to work without error? Could you please further explain how the datetime format works? i've spent hours trying to research this and nothing seems to work?

**Comment by alexschimpf** [comment]
Have you tried something like: "YYY-MM-DD HH:MM:SS"?

**Comment by TheBoss572** [comment]
nvm i was just making a stupid mistake in the format. also why does sometimes it show "AN ERROR OCCURRED.
We are unable to connect to our servers right now. Please try again later." when logging in? and can this be fixed or is it just the syntax i'm using?

**Comment by TheBoss572** [comment]
> Have you tried something like: "YYYY-MM-DD HH:MM:SS"?

doesn’t work

**Comment by TheBoss572** [comment]
you dead?

**Comment by TheBoss572** [comment]
how am I supposed to put something in the format of YYYY-MM-DD HH:MM:SS when a space in the syntax would be recognized as another argument? I'm probably missing something. I'd appreciate some extra specification but you seemed to have dipped out.

**Comment by TheBoss572** [comment]
> Have you tried something like: "YYYY-MM-DD HH:MM:SS"?

how am I supposed to put something in the format of YYYY-MM-DD HH:MM:SS when a space in the syntax would be recognized as another argument? I'm probably missing something. I'd appreciate some extra specification but you seemed to have dipped out.

**Comment by alexschimpf** [comment]
Just put double quotes around it so it will be interpreted as one arg.

**Comment by TheBoss572** [comment]
I put " --release-time "2020-11-17 14:05:10" " and it says it's an invalid format string. what am I doing wrong? I apologize for being this dumb.

**Comment by TheBoss572** [comment]
I put " --release-time "2020-11-17 14:05:10" " and it still says it is an invalid format string. What am I doing wrong? I apologize for being so dumb.

**Comment by ericruiz-developer** [comment]
> I put " --release-time "2020-11-17 14:05:10" " and it still says it is an invalid format string. What am I doing wrong? I apologize for being so dumb.

Can you post a code snippet so we can get a better idea of what you have? That would really help the debug process.

**Comment by TheBoss572** [comment]
> > I put " --release-time "2020-11-17 14:05:10" " and it still says it is an invalid format string. What am I doing wrong? I apologize for being so dumb.
> 
> Can you post a code snippet so we can get a better idea of what you have? That would really help the debug process.

python main.py --username username --password password --shoe-size 10.5 --url https://nike.com/examplewhatever --release-time "2020-11-17 15:40:10" --driver-type firefox --webdriver-path C:\Windows\System32\geckodriver.exe --num-retries 100 --shoe-type M

**Comment by alexschimpf** [comment]
@TheBoss572 Could you also give the exact error message you're getting? It's working just fine for me on Mac (not sure about Windows).

**Comment by TheBoss572** [comment]
It gives me this error everytime even though it seems to be recognizing the time format i'm putting it in? : 2020-11-18 08:26:59,548 [PID 6552] [Thread 7472] [INFO] [root] Requesting page: https://www.nike.com/login
2020-11-18 08:27:02,473 [PID 6552] [Thread 7472] [INFO] [root] Waiting for login fields to become visible
2020-11-18 08:27:02,488 [PID 6552] [Thread 7472] [INFO] [root] Entering username and password
2020-11-18 08:27:03,545 [PID 6552] [Thread 7472] [INFO] [root] Logging in
2020-11-18 08:27:04,677 [PID 6552] [Thread 7472] [INFO] [root] Successfully logged in
2020-11-18 08:27:04,677 [PID 6552] [Thread 7472] [INFO] [root] Waiting until release time: 2020-11-18 09:40:10
Traceback (most recent call last):
  File "main.py", line 293, in <module>
    run(driver=driver, shoe_type=shoe_type, username=args.username, password=args.password, url=args.url, shoe_size=args.shoe_size,
  File "main.py", line 62, in run
    pause.until(date_parser.parse(release_time))
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pause\__init__.py", line 46, in until
    end = float(time.strftime('%s.%f'))
ValueError: Invalid format string

**Comment by alexschimpf** [comment]
This seems like a bug in the `pause` module. On Windows, looks like "%s.%f" is not a valid format for `strftime`.

**Windows**: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?redirectedfrom=MSDN&view=msvc-160
**Python**: https://strftime.org/

One workaround is to run `strftime` on the release time with a valid Windows-style format before passing it to `pause.until`.

**Comment by TheBoss572** [comment]
> This seems like a bug in the `pause` module. On Windows, looks like "%s.%f" is not a valid format for `strftime`.
> 
> **Windows**: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?redirectedfrom=MSDN&view=msvc-160
> **Python**: https://strftime.org/
> 
> One workaround is to run `strftime` on the release time with a valid Windows-style format before passing it to `pause.until`.

How would I do that? I'm not super experienced with python...

**Comment by zbeve** [comment]
I've run into the same issue.

Replacing line 79 `pause.until(date_parser.parse(release_time))` with these two lines:
`wait_duration = (date_parser.parse(release_time) - datetime.datetime.now()).total_seconds()`
`pause.seconds(int(wait_duration))`
should get the job done.

You would also need to `import datetime` for this to work

Only tested locally though, haven't tried to use it during a purchase, so no guarantees.
