### ISSUE TITLE
Bot stops after logging into nike.

### ISSUE THREAD

**Issue by schmackz** [alexschimpf/Snkrs-Bot#39]
The bot will navigate to nike login. If it gets the error, it dismisses it and then logs in. And then it just sits at the nike main page.

**Comment by mnai01** [comment]
Do you have any additional settings in the params running? Can I see your execution code?

**Comment by schmackz** [comment]
C:\Users\Dell\Desktop\newbot\Snkrs-Bot>python3 main.py --username ******** --password ***** --url https://www.nike.com/launch/t/air-jordan-11-adapt --shoe-size 6 --driver-type chrome
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\newbot\Snkrs-Bot\main.py", line 3, in <module>
    import six
ModuleNotFoundError: No module named 'six'

C:\Users\Dell\Desktop\newbot\Snkrs-Bot>python main.py --username wholetimetray@gmail.com --password Sh@fter808 --url https://www.nike.com/launch/t/air-jordan-11-adapt --shoe-size 6 --driver-type chrome

DevTools listening on ws://127.0.0.1:60258/devtools/browser/085b5b03-e1e6-44a9-af84-4374bcb4afc8
2020-12-29 18:14:19,375 [PID 11112] [Thread 6120] [INFO] [root] Requesting page: https://www.nike.com/login
[2744:14904:1229/181420.389:ERROR:device_event_log_impl.cc(211)] [18:14:20.389] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[2744:14904:1229/181420.402:ERROR:device_event_log_impl.cc(211)] [18:14:20.403] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
2020-12-29 18:14:20,790 [PID 11112] [Thread 6120] [INFO] [root] Waiting for login fields to become visible
2020-12-29 18:14:22,840 [PID 11112] [Thread 6120] [INFO] [root] Entering username and password
2020-12-29 18:14:23,693 [PID 11112] [Thread 6120] [INFO] [root] Logging in
2020-12-29 18:14:28,930 [PID 11112] [Thread 6120] [INFO] [root] Failed to login due to timeout. Retrying...
2020-12-29 18:14:29,174 [PID 11112] [Thread 6120] [INFO] [root] Logging in
2020-12-29 18:14:32,887 [PID 11112] [Thread 6120] [ERROR] [root] Error dialog did not load, proceed. Error: Message: timeout: Timed out receiving message from renderer: 2.000
  (Session info: chrome=87.0.4280.88)
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\newbot\Snkrs-Bot\main.py", line 176, in retry_login
    wait_until_visible(driver=driver, xpath=xpath, duration=5)
  File "C:\Users\Dell\Desktop\newbot\Snkrs-Bot\main.py", line 286, in wait_until_visible
    WebDriverWait(driver, duration, frequency).until(EC.visibility_of_element_located((By.XPATH, xpath)))
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 964, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 2.000
  (Session info: chrome=87.0.4280.88)

[3392:13088:1229/181508.135:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181508.389:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181508.437:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181508.500:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181508.522:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181508.523:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181534.188:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181534.435:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181556.100:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181556.318:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/182149.990:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/182553.505:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/182553.805:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101

**Comment by schmackz** [comment]
> Do you have any additional settings in the params running? Can I see your execution code?

C:\Users\Dell\Desktop\newbot\Snkrs-Bot>python3 main.py --username ******** --password ***** --url https://www.nike.com/launch/t/air-jordan-11-adapt --shoe-size 6 --driver-type chrome
Traceback (most recent call last):
File "C:\Users\Dell\Desktop\newbot\Snkrs-Bot\main.py", line 3, in
import six
ModuleNotFoundError: No module named 'six'

C:\Users\Dell\Desktop\newbot\Snkrs-Bot>python main.py --username ****** --password ****** --url https://www.nike.com/launch/t/air-jordan-11-adapt --shoe-size 6 --driver-type chrome

DevTools listening on ws://127.0.0.1:60258/devtools/browser/085b5b03-e1e6-44a9-af84-4374bcb4afc8
2020-12-29 18:14:19,375 [PID 11112] [Thread 6120] [INFO] [root] Requesting page: https://www.nike.com/login
[2744:14904:1229/181420.389:ERROR:device_event_log_impl.cc(211)] [18:14:20.389] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[2744:14904:1229/181420.402:ERROR:device_event_log_impl.cc(211)] [18:14:20.403] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
2020-12-29 18:14:20,790 [PID 11112] [Thread 6120] [INFO] [root] Waiting for login fields to become visible
2020-12-29 18:14:22,840 [PID 11112] [Thread 6120] [INFO] [root] Entering username and password
2020-12-29 18:14:23,693 [PID 11112] [Thread 6120] [INFO] [root] Logging in
2020-12-29 18:14:28,930 [PID 11112] [Thread 6120] [INFO] [root] Failed to login due to timeout. Retrying...
2020-12-29 18:14:29,174 [PID 11112] [Thread 6120] [INFO] [root] Logging in
2020-12-29 18:14:32,887 [PID 11112] [Thread 6120] [ERROR] [root] Error dialog did not load, proceed. Error: Message: timeout: Timed out receiving message from renderer: 2.000
(Session info: chrome=87.0.4280.88)
Traceback (most recent call last):
File "C:\Users\Dell\Desktop\newbot\Snkrs-Bot\main.py", line 176, in retry_login
wait_until_visible(driver=driver, xpath=xpath, duration=5)
File "C:\Users\Dell\Desktop\newbot\Snkrs-Bot\main.py", line 286, in wait_until_visible
WebDriverWait(driver, duration, frequency).until(EC.visibility_of_element_located((By.XPATH, xpath)))
File "C:\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
value = method(self._driver)
File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in call
return _element_if_visible(_find_element(driver, self.locator))
File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
raise e
File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
return driver.find_element(*by)
File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 964, in find_element
return self.execute(Command.FIND_ELEMENT, {
File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
self.error_handler.check_response(response)
File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 2.000
(Session info: chrome=87.0.4280.88)

[3392:13088:1229/181508.135:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181508.389:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181508.437:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181508.500:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181508.522:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181508.523:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181534.188:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181534.435:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181556.100:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/181556.318:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/182149.990:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/182553.505:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[3392:13088:1229/182553.805:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101

**Comment by mnai01** [comment]
You have to install the packages required to run the main.py script. To do that try to run pip install on the requirements.txt file 

`pip install -r C:\Users\Dell\Desktop\newbot\Snkrs-Bot\requirements.txt` 

or you can install each package individually with


`pip install pause==0.1.2`
`pip install python-dateutil==2.7.3`
`pip install selenium==3.14.0`
`pip install six==1.11.0`
`pip install urllib3==1.24.2`

**Comment by schmackz** [comment]
> You have to install the packages required to run the main.py script. To do that try to run pip install on the requirements.txt file
> 
> `pip install -r C:\Users\Dell\Desktop\newbot\Snkrs-Bot\requirements.txt`
> 
> or you can install each package individually with
> 
> `pip install pause==0.1.2`
> `pip install python-dateutil==2.7.3`
> `pip install selenium==3.14.0`
> `pip install six==1.11.0`
> `pip install urllib3==1.24.2`

I did install from requirements.txt.

I just went thru individually as you suggested:

C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install six==1.11.0
Requirement already satisfied: six==1.11.0 in c:\python39\lib\site-packages (1.11.0)
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.

C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install pause==0.1.2
Requirement already satisfied: pause==0.1.2 in c:\python39\lib\site-packages (0.1.2)
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.

C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install selenuium==3.14.0
ERROR: Could not find a version that satisfies the requirement selenuium==3.14.0
ERROR: No matching distribution found for selenuium==3.14.0
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.

C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install python-dateutil==2.7.3
Requirement already satisfied: python-dateutil==2.7.3 in c:\python39\lib\site-packages (2.7.3)
Requirement already satisfied: six>=1.5 in c:\python39\lib\site-packages (from python-dateutil==2.7.3) (1.11.0)
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.

C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install urllib3==1.24.2
Requirement already satisfied: urllib3==1.24.2 in c:\python39\lib\site-packages (1.24.2)
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.

**Comment by mnai01** [comment]
> > You have to install the packages required to run the main.py script. To do that try to run pip install on the requirements.txt file
> > `pip install -r C:\Users\Dell\Desktop\newbot\Snkrs-Bot\requirements.txt`
> > or you can install each package individually with
> > `pip install pause==0.1.2`
> > `pip install python-dateutil==2.7.3`
> > `pip install selenium==3.14.0`
> > `pip install six==1.11.0`
> > `pip install urllib3==1.24.2`
> 
> I did install from requirements.txt.
> 
> I just went thru individually as you suggested:
> 
> C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install six==1.11.0
> Requirement already satisfied: six==1.11.0 in c:\python39\lib\site-packages (1.11.0)
> WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.
> 
> C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install pause==0.1.2
> Requirement already satisfied: pause==0.1.2 in c:\python39\lib\site-packages (0.1.2)
> WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.
> 
> C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install selenium==3.14.0
> Requirement already satisfied: selenium==3.14.0 in c:\python39\lib\site-packages (3.14.0)
> Requirement already satisfied: urllib3 in c:\python39\lib\site-packages (from selenium==3.14.0) (1.24.2)
> WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.
> 
> C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install python-dateutil==2.7.3
> Requirement already satisfied: python-dateutil==2.7.3 in c:\python39\lib\site-packages (2.7.3)
> Requirement already satisfied: six>=1.5 in c:\python39\lib\site-packages (from python-dateutil==2.7.3) (1.11.0)
> WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.
> 
> C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install urllib3==1.24.2
> Requirement already satisfied: urllib3==1.24.2 in c:\python39\lib\site-packages (1.24.2)
> WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.

What happens when you run it now?

**Comment by schmackz** [comment]
> > > You have to install the packages required to run the main.py script. To do that try to run pip install on the requirements.txt file
> > > `pip install -r C:\Users\Dell\Desktop\newbot\Snkrs-Bot\requirements.txt`
> > > or you can install each package individually with
> > > `pip install pause==0.1.2`
> > > `pip install python-dateutil==2.7.3`
> > > `pip install selenium==3.14.0`
> > > `pip install six==1.11.0`
> > > `pip install urllib3==1.24.2`
> > 
> > 
> > I did install from requirements.txt.
> > I just went thru individually as you suggested:
> > C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install six==1.11.0
> > Requirement already satisfied: six==1.11.0 in c:\python39\lib\site-packages (1.11.0)
> > WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> > You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.
> > C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install pause==0.1.2
> > Requirement already satisfied: pause==0.1.2 in c:\python39\lib\site-packages (0.1.2)
> > WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> > You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.
> > C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install selenium==3.14.0
> > Requirement already satisfied: selenium==3.14.0 in c:\python39\lib\site-packages (3.14.0)
> > Requirement already satisfied: urllib3 in c:\python39\lib\site-packages (from selenium==3.14.0) (1.24.2)
> > WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> > You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.
> > C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install python-dateutil==2.7.3
> > Requirement already satisfied: python-dateutil==2.7.3 in c:\python39\lib\site-packages (2.7.3)
> > Requirement already satisfied: six>=1.5 in c:\python39\lib\site-packages (from python-dateutil==2.7.3) (1.11.0)
> > WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> > You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.
> > C:\Users\Dell\Desktop\newbot\Snkrs-Bot>pip install urllib3==1.24.2
> > Requirement already satisfied: urllib3==1.24.2 in c:\python39\lib\site-packages (1.24.2)
> > WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> 
> What happens when you run it now?

it wont run using python3 command. Same six error. Using just the python command:

C:\Users\Dell\Desktop\newbot\Snkrs-Bot>python3 main.py --username ****** --password *** --url https://www.nike.com/launch/t/air-jordan-11-adapt --shoe-size 6 --driver-type chrome
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\newbot\Snkrs-Bot\main.py", line 3, in <module>
    import six
ModuleNotFoundError: No module named 'six'

C:\Users\Dell\Desktop\newbot\Snkrs-Bot>python main.py --username ***** --password ****** --url https://www.nike.com/launch/t/air-jordan-11-adapt --shoe-size 6 --driver-type chrome

DevTools listening on ws://127.0.0.1:64429/devtools/browser/d2198135-6a52-44f7-a79b-7c9b0e9ceb8d
2020-12-29 20:48:17,074 [PID 5020] [Thread 13260] [INFO] [root] Requesting page: https://www.nike.com/login
[13220:10760:1229/204818.105:ERROR:device_event_log_impl.cc(211)] [20:48:18.105] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[13220:10760:1229/204818.136:ERROR:device_event_log_impl.cc(211)] [20:48:18.136] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[13220:10760:1229/204818.146:ERROR:device_event_log_impl.cc(211)] [20:48:18.147] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
2020-12-29 20:48:19,313 [PID 5020] [Thread 13260] [INFO] [root] Waiting for login fields to become visible
2020-12-29 20:48:22,915 [PID 5020] [Thread 13260] [INFO] [root] Entering username and password
2020-12-29 20:48:23,275 [PID 5020] [Thread 13260] [INFO] [root] Logging in
2020-12-29 20:48:28,434 [PID 5020] [Thread 13260] [INFO] [root] Failed to login due to timeout. Retrying...
2020-12-29 20:48:28,654 [PID 5020] [Thread 13260] [INFO] [root] Logging in
2020-12-29 20:48:29,008 [PID 5020] [Thread 13260] [INFO] [root] Logging in
2020-12-29 20:48:32,116 [PID 5020] [Thread 13260] [ERROR] [root] Error dialog did not load, proceed. Error: Message: timeout: Timed out receiving message from renderer: 2.000
  (Session info: chrome=87.0.4280.88)
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\newbot\Snkrs-Bot\main.py", line 176, in retry_login
    wait_until_visible(driver=driver, xpath=xpath, duration=5)
  File "C:\Users\Dell\Desktop\newbot\Snkrs-Bot\main.py", line 286, in wait_until_visible
    WebDriverWait(driver, duration, frequency).until(EC.visibility_of_element_located((By.XPATH, xpath)))
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 964, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 2.000
  (Session info: chrome=87.0.4280.88)

[15308:3144:1229/204923.196:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[15308:3144:1229/204923.510:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[15308:3144:1229/204923.524:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[15308:3144:1229/204923.525:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[15308:3144:1229/204923.525:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[15308:3144:1229/204923.526:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101

**Comment by mnai01** [comment]
You might have multiple versions of python on ur system and pip is installing the packages on one version but not the other. If you try to run the script using the version where pip is NOT installing the packages then you can get an error like yours. Try this instead.

`python3 -m pip install pause==0.1.2`
`python3 -m pip install python-dateutil==2.7.3`
`python3 -m pip install selenium==3.14.0`
`python3 -m pip install six==1.11.0`
`python3 -m pip install urllib3==1.24.2`

**Comment by schmackz** [comment]
> You might have multiple versions of python on ur system and pip is installing the packages on one version but not the other. If you try to run the script using the version where pip is NOT installing the packages then you can get an error like yours. Try this instead.
> 
> `python3 -m pip install pause==0.1.2`
> `python3 -m pip install python-dateutil==2.7.3`
> `python3 -m pip install selenium==3.14.0`
> `python3 -m pip install six==1.11.0`
> `python3 -m pip install urllib3==1.24.2`

I dont know why i didn't think about the multiple versions. I definitely do.. I work in GIS.. 

Got the packages installed but still:

PS C:\Users\Dell\desktop\newbot\snkrs-bot> python3 main.py --username ******* --password ***** --url https://www.nike.com/launch/t/air-jordan-11-adapt --shoe-size 6 --driver-type chrome

DevTools listening on ws://127.0.0.1:65486/devtools/browser/76d9a6ad-4cb8-42b3-a9f1-33981241482e
[3804:14508:1229/210119.035:ERROR:device_event_log_impl.cc(211)] [21:01:19.035] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[3804:14508:1229/210119.037:ERROR:device_event_log_impl.cc(211)] [21:01:19.037] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
2020-12-29 21:01:22,108 [PID 10380] [Thread 9512] [INFO] [root] Requesting page: https://www.nike.com/login
2020-12-29 21:01:23,612 [PID 10380] [Thread 9512] [INFO] [root] Waiting for login fields to become visible
2020-12-29 21:01:25,631 [PID 10380] [Thread 9512] [INFO] [root] Entering username and password
2020-12-29 21:01:26,385 [PID 10380] [Thread 9512] [INFO] [root] Logging in
2020-12-29 21:01:32,155 [PID 10380] [Thread 9512] [INFO] [root] Failed to login due to timeout. Retrying...
2020-12-29 21:01:32,365 [PID 10380] [Thread 9512] [INFO] [root] Logging in
2020-12-29 21:01:32,742 [PID 10380] [Thread 9512] [INFO] [root] Logging in
2020-12-29 21:01:37,268 [PID 10380] [Thread 9512] [ERROR] [root] Error dialog did not load, proceed. Error: Message: timeout: Timed out receiving message from renderer: 2.000
  (Session info: chrome=87.0.4280.88)
Traceback (most recent call last):
  File "C:\Users\Dell\desktop\newbot\snkrs-bot\main.py", line 176, in retry_login
    wait_until_visible(driver=driver, xpath=xpath, duration=5)
  File "C:\Users\Dell\desktop\newbot\snkrs-bot\main.py", line 286, in wait_until_visible
    WebDriverWait(driver, duration, frequency).until(EC.visibility_of_element_located((By.XPATH, xpath)))
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 964, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 2.000
  (Session info: chrome=87.0.4280.88)

[6496:8596:1229/210153.961:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[6496:8596:1229/210153.988:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[6496:8596:1229/210213.177:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101

**Comment by mnai01** [comment]
Great, looks like the module problem is fixed!

Now this problem is most likely related to a chrome driver issue. I use firefox when running the script because I can't update my google chrome but to fix this problem I would recommend 

- Make sure your chrome is updated. 

- Switch the chrome driver in the bin folder with a more updated version or the correct version that matches your chrome (make sure to make the new file match the old files name) [Download Here](https://chromedriver.chromium.org/downloads)

- Switch to firefox (I had to replace the firefox driver in the bin folder with the most updated driver online) [Download Here](https://github.com/mozilla/geckodriver/releases)

**Comment by schmackz** [comment]
> Great, looks like the module problem is fixed!
> 
> Now this problem is most likely related to a chrome driver issue. I use firefox when running the script because I can't update my google chrome but to fix this problem I would recommend
> 
> * Make sure your chrome is updated.
> * Switch the chrome driver in the bin folder with a more updated version or the correct version that matches your chrome (make sure to make the new file match the old files name) [Download Here](https://chromedriver.chromium.org/downloads)
> * Switch to firefox (I had to replace the firefox driver in the bin folder with the most updated driver online) [Download Here](https://github.com/mozilla/geckodriver/releases)

Bro, Thanks for all your help. Definitely works best in firefox.

**Comment by Johvonny** [comment]
@schmackz Do you think you could send me what you made out of reference?  new to the process and im lost.
