### ISSUE TITLE
Geckodriver Trouble

### ISSUE THREAD

**Issue by Sneaks1213** [alexschimpf/Snkrs-Bot#49]
Hi all, 

I apologize I am very new to this and spent a couple hours this morning trying to figure this out myself but not moving very far very fast. I have installed all the requirements and I feel like I have been pretty thorough but this is the error that I keep getting. Can someone help me out. 

Cheers!

python3 main.py --username ******************** --password ********** --url https://www.nike.com/launch/t/jordan-why-not-zer04-upbringing --shoe-size 12.5 --shoe-type M --driver-type firefox --cvv **** --shipping-option STANDARD --shipping-address '{"first_name":"*****", "last_name":"****", "address":"************", "apt":"", "city":"*************", "state":"**", "zip_code":"*****", "phone_number":"*********"}' --page-load-timeout 3 --headless --purchase --dont-quit
/Users/code/main.py:644: DeprecationWarning: use service_log_path instead of log_path
  driver = webdriver.Firefox(executable_path=executable_path, firefox_options=options, log_path=os.devnull)
/Users/code/main.py:644: DeprecationWarning: use options instead of firefox_options
  driver = webdriver.Firefox(executable_path=executable_path, firefox_options=options, log_path=os.devnull)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './bin/geckodriver_mac'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/code/main.py", line 644, in <module>
    driver = webdriver.Firefox(executable_path=executable_path, firefox_options=options, log_path=os.devnull)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver_mac' executable needs to be in PATH.'

**Comment by Sneaks1213** [comment]
Sorry guys I am a dumbass, I think I figured it out. Sorry for opening an issue
