### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 86

### ISSUE THREAD

**Issue by jcoltrin70** [alexschimpf/Snkrs-Bot#86]
I believe I have all prerequisite installations configured correctly. On Windows 10 when I run the command:

python main.py --username username@gmail.com --password P@ssw0rd --url https://www.nike.com/launch/t/air-jordan-1-patent-bred --shoe-size 10 --shoe-type M --cvv 570 --driver-type chrome

I get the following output:
`DevTools listening on ws://127.0.0.1:57838/devtools/browser/46f55807-3ce0-4995-9b04-3d83f613c3f7
Traceback (most recent call last):
  File "c:\Users\Jason\Documents\Projects\Nike Buy Bot\Snkrs-Bot\main.py", line 659, in <module>
    driver = webdriver.Chrome(executable_path=executable_path, chrome_options=options)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 71, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 86
Current browser version is 96.0.4664.110 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe`

The last 2 lines caught my eye: This version of ChromeDriver only supports Chrome version 86... I guess I could try to find a version of Chrome ver 86 somewhere, then install/run this in a vm, but I prefer not to. Do you have a workaround for this issue?

**Comment by TechWithTy** [comment]
You need to download the correct version of chrome driver from the website and replace it in the "Bin folder"
https://chromedriver.storage.googleapis.com/index.html?path=99.0.4844.51/
